name: chatui
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  flutter_screenutil: ^5.8.4
  flutter_slidable: ^3.0.0
  cached_network_image: ^3.2.3
  internet_connection_checker: ^1.0.0+1


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  #  assets:
  #     - images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
        - weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
        - weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
        - weight: 300

    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf

